//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaPrestamos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moras
    {
        public int Id { get; set; }
        public Nullable<int> PrestamoId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> MontoMora { get; set; }
    
        public virtual Prestamos Prestamos { get; set; }
    }
}
