//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaPrestamos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamos
    {
        public Prestamos()
        {
            this.Moras = new HashSet<Moras>();
            this.Pagos = new HashSet<Pagos>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<int> TiempoMeses { get; set; }
        public Nullable<decimal> TasaInteres { get; set; }
        public Nullable<decimal> InteresGenerado { get; set; }
        public Nullable<decimal> MontoTotal { get; set; }
        public Nullable<decimal> SaldoRestante { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public string Estado { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual ICollection<Moras> Moras { get; set; }
        public virtual ICollection<Pagos> Pagos { get; set; }
    }
}
